### ISSUE TITLE
update Chain & Pattern (@Joey)

### ISSUE THREAD

**Issue by Scya597** [vibertthio/beact#11]
update Chain的時候希望能讓chainlist裡頭被update的chainElement閃一下（旁邊有打勾的那個）
update Pattern同理。

**Comment by csiejoey** [comment]
當下被選取之pattern打勾

**Comment by csiejoey** [comment]
在沒有輸入 title 的情況下試圖 update 或 save 時，希望能在Title的輸入欄下跳出暫時性的紅字警告

**Comment by vibertthio** [comment]
- Patter List / Chain List 的文字對齊設定
- hover on 的效果
- 開頭的 logo 顯示
